/-
Machine-generated by tools/lean_verify.py — do not edit.

Case:      claim-late-notice-escalated
Reference: claim_eligibility/flow.json   (flow id: claim-eligibility-v1)
Extracted: extracted/claim-late-notice-escalated.json
Document:  claim_eligibility/clause_divergent.md

Verifies whether the flow extracted from the document is equivalent to the
reference flow over every assignment satisfying the ontology constraints.
Lean toolchain: 4.32.1, core only (no mathlib).
-/
set_option maxRecDepth 100000

structure Assignment where
  policy_in_force : Bool
  excluded_peril : Bool
  loss_exceeds_deductible : Bool
  notice_within_30_days : Bool
  documentation_complete : Bool
deriving Repr, DecidableEq

inductive Outcome where
  | DENIED
  | BELOW_DEDUCTIBLE
  | FULL_PAYMENT
  | REDUCED_PAYMENT
deriving Repr, DecidableEq, BEq

def valid (_ : Assignment) : Bool :=
  true

-- Reference flow (claim-eligibility-v1)
def reference_o_denied (_ : Assignment) : Outcome := .DENIED
def reference_o_full (_ : Assignment) : Outcome := .FULL_PAYMENT
def reference_o_reduced (_ : Assignment) : Outcome := .REDUCED_PAYMENT
def reference_n5 (a : Assignment) : Outcome :=
  if a.documentation_complete then reference_o_full a else reference_o_reduced a
def reference_n4 (a : Assignment) : Outcome :=
  if a.notice_within_30_days then reference_n5 a else reference_o_reduced a
def reference_o_below (_ : Assignment) : Outcome := .BELOW_DEDUCTIBLE
def reference_n3 (a : Assignment) : Outcome :=
  if a.loss_exceeds_deductible then reference_n4 a else reference_o_below a
def reference_n2 (a : Assignment) : Outcome :=
  if a.excluded_peril then reference_o_denied a else reference_n3 a
def reference_n1 (a : Assignment) : Outcome :=
  if a.policy_in_force then reference_n2 a else reference_o_denied a
def reference : Assignment → Outcome := reference_n1

-- Extracted flow (from claim_eligibility/clause_divergent.md)
def extracted_x_den (_ : Assignment) : Outcome := .DENIED
def extracted_x_full (_ : Assignment) : Outcome := .FULL_PAYMENT
def extracted_x_red (_ : Assignment) : Outcome := .REDUCED_PAYMENT
def extracted_e5 (a : Assignment) : Outcome :=
  if a.documentation_complete then extracted_x_full a else extracted_x_red a
def extracted_e4 (a : Assignment) : Outcome :=
  if a.notice_within_30_days then extracted_e5 a else extracted_x_den a
def extracted_x_below (_ : Assignment) : Outcome := .BELOW_DEDUCTIBLE
def extracted_e3 (a : Assignment) : Outcome :=
  if a.loss_exceeds_deductible then extracted_e4 a else extracted_x_below a
def extracted_e2 (a : Assignment) : Outcome :=
  if a.excluded_peril then extracted_x_den a else extracted_e3 a
def extracted_e1 (a : Assignment) : Outcome :=
  if a.policy_in_force then extracted_e2 a else extracted_x_den a
def extracted : Assignment → Outcome := extracted_e1

def bools : List Bool := [false, true]

/-- Every assignment of the 5 atoms (32 in total). -/
def allAssignments : List Assignment :=
  bools.flatMap fun policy_in_force =>
  bools.flatMap fun excluded_peril =>
  bools.flatMap fun loss_exceeds_deductible =>
  bools.flatMap fun notice_within_30_days =>
  bools.map fun documentation_complete =>
    { policy_in_force, excluded_peril, loss_exceeds_deductible, notice_within_30_days, documentation_complete }

/-- Valid assignments where the two flows disagree. -/
def counterexamples : List Assignment :=
  allAssignments.filter fun a => valid a && !(reference a == extracted a)

#eval IO.println s!"TOTAL {allAssignments.length}"
#eval IO.println s!"VALID {(allAssignments.filter valid).length}"
#eval IO.println s!"COUNTEREXAMPLES {counterexamples.length}"
#eval counterexamples.forM fun a => IO.println s!"CX {reprStr a}"

/-- The document diverges from the reference logic: there is a legally
possible assignment on which the two flows disagree. Kernel-checked. -/
theorem divergent : counterexamples ≠ [] := by decide

/-- Exactly 2 valid assignments diverge. Kernel-checked. -/
theorem divergent_count : counterexamples.length = 2 := by decide
