/-
Machine-generated by tools/lean_verify.py — do not edit.

Case:      severance-constructive-dismissal-dropped
Reference: termination_severance/flow.json   (flow id: termination-severance-v2)
Extracted: extracted/severance-constructive-dismissal-dropped.json
Document:  termination_severance/clause_divergent_constructive_dropped.md

Verifies whether the flow extracted from the document is equivalent to the
reference flow over every assignment satisfying the ontology constraints.
Lean toolchain: 4.32.1, core only (no mathlib).
-/
set_option maxRecDepth 100000

structure Assignment where
  terminated_for_cause : Bool
  gross_misconduct : Bool
  voluntary_resignation : Bool
  constructive_dismissal : Bool
  served_12_months : Bool
  served_5_years : Bool
  redundancy : Bool
  suitable_alternative_offered : Bool
  written_notice_given : Bool
deriving Repr, DecidableEq

inductive Outcome where
  | NO_SEVERANCE
  | STATUTORY_MINIMUM
  | STANDARD_SEVERANCE
  | ENHANCED_SEVERANCE
  | PREMIUM_REDUNDANCY
deriving Repr, DecidableEq, BEq

def valid (a : Assignment) : Bool :=
  (!a.gross_misconduct || a.terminated_for_cause)
  && (!a.constructive_dismissal || a.voluntary_resignation)
  && (!a.served_5_years || a.served_12_months)
  && (!a.suitable_alternative_offered || a.redundancy)
  && !(a.terminated_for_cause && a.voluntary_resignation)
  && !(a.terminated_for_cause && a.redundancy)
  && !(a.voluntary_resignation && a.redundancy)

-- Reference flow (termination-severance-v2)
def reference_o_none (_ : Assignment) : Outcome := .NO_SEVERANCE
def reference_o_statutory (_ : Assignment) : Outcome := .STATUTORY_MINIMUM
def reference_n3 (a : Assignment) : Outcome :=
  if a.served_5_years then reference_o_statutory a else reference_o_none a
def reference_n2 (a : Assignment) : Outcome :=
  if a.gross_misconduct then reference_o_none a else reference_n3 a
def reference_o_standard (_ : Assignment) : Outcome := .STANDARD_SEVERANCE
def reference_o_premium (_ : Assignment) : Outcome := .PREMIUM_REDUNDANCY
def reference_o_enhanced (_ : Assignment) : Outcome := .ENHANCED_SEVERANCE
def reference_n9 (a : Assignment) : Outcome :=
  if a.served_5_years then reference_o_premium a else reference_o_enhanced a
def reference_n8 (a : Assignment) : Outcome :=
  if a.suitable_alternative_offered then reference_o_standard a else reference_n9 a
def reference_n11 (a : Assignment) : Outcome :=
  if a.served_5_years then reference_o_enhanced a else reference_o_standard a
def reference_n10 (a : Assignment) : Outcome :=
  if a.written_notice_given then reference_n11 a else reference_o_enhanced a
def reference_n7 (a : Assignment) : Outcome :=
  if a.redundancy then reference_n8 a else reference_n10 a
def reference_n6 (a : Assignment) : Outcome :=
  if a.served_12_months then reference_n7 a else reference_o_statutory a
def reference_n5 (a : Assignment) : Outcome :=
  if a.constructive_dismissal then reference_n6 a else reference_o_none a
def reference_n4 (a : Assignment) : Outcome :=
  if a.voluntary_resignation then reference_n5 a else reference_n6 a
def reference_n1 (a : Assignment) : Outcome :=
  if a.terminated_for_cause then reference_n2 a else reference_n4 a
def reference : Assignment → Outcome := reference_n1

-- Extracted flow (from termination_severance/clause_divergent_constructive_dropped.md)
def extracted_x_none (_ : Assignment) : Outcome := .NO_SEVERANCE
def extracted_x_stat (_ : Assignment) : Outcome := .STATUTORY_MINIMUM
def extracted_e2b (a : Assignment) : Outcome :=
  if a.served_5_years then extracted_x_stat a else extracted_x_none a
def extracted_e2 (a : Assignment) : Outcome :=
  if a.gross_misconduct then extracted_x_none a else extracted_e2b a
def extracted_x_std (_ : Assignment) : Outcome := .STANDARD_SEVERANCE
def extracted_x_prem (_ : Assignment) : Outcome := .PREMIUM_REDUNDANCY
def extracted_x_enh (_ : Assignment) : Outcome := .ENHANCED_SEVERANCE
def extracted_e8 (a : Assignment) : Outcome :=
  if a.served_5_years then extracted_x_prem a else extracted_x_enh a
def extracted_e7 (a : Assignment) : Outcome :=
  if a.suitable_alternative_offered then extracted_x_std a else extracted_e8 a
def extracted_e10 (a : Assignment) : Outcome :=
  if a.served_5_years then extracted_x_enh a else extracted_x_std a
def extracted_e9 (a : Assignment) : Outcome :=
  if a.written_notice_given then extracted_e10 a else extracted_x_enh a
def extracted_e6 (a : Assignment) : Outcome :=
  if a.redundancy then extracted_e7 a else extracted_e9 a
def extracted_e5 (a : Assignment) : Outcome :=
  if a.served_12_months then extracted_e6 a else extracted_x_stat a
def extracted_e3 (a : Assignment) : Outcome :=
  if a.voluntary_resignation then extracted_x_none a else extracted_e5 a
def extracted_e1 (a : Assignment) : Outcome :=
  if a.terminated_for_cause then extracted_e2 a else extracted_e3 a
def extracted : Assignment → Outcome := extracted_e1

def bools : List Bool := [false, true]

/-- Every assignment of the 9 atoms (512 in total). -/
def allAssignments : List Assignment :=
  bools.flatMap fun terminated_for_cause =>
  bools.flatMap fun gross_misconduct =>
  bools.flatMap fun voluntary_resignation =>
  bools.flatMap fun constructive_dismissal =>
  bools.flatMap fun served_12_months =>
  bools.flatMap fun served_5_years =>
  bools.flatMap fun redundancy =>
  bools.flatMap fun suitable_alternative_offered =>
  bools.map fun written_notice_given =>
    { terminated_for_cause, gross_misconduct, voluntary_resignation, constructive_dismissal, served_12_months, served_5_years, redundancy, suitable_alternative_offered, written_notice_given }

/-- Valid assignments where the two flows disagree. -/
def counterexamples : List Assignment :=
  allAssignments.filter fun a => valid a && !(reference a == extracted a)

#eval IO.println s!"TOTAL {allAssignments.length}"
#eval IO.println s!"VALID {(allAssignments.filter valid).length}"
#eval IO.println s!"COUNTEREXAMPLES {counterexamples.length}"
#eval counterexamples.forM fun a => IO.println s!"CX {reprStr a}"

/-- The document diverges from the reference logic: there is a legally
possible assignment on which the two flows disagree. Kernel-checked. -/
theorem divergent : counterexamples ≠ [] := by decide

/-- Exactly 6 valid assignments diverge. Kernel-checked. -/
theorem divergent_count : counterexamples.length = 6 := by decide
