#!/usr/bin/env python3
"""Lean-based verification of extracted flows against reference flows.

For every case in examples/index.json this tool:

  1. Compiles the reference flow, the chat-extracted flow, and the ontology
     constraints into a self-contained Lean 4 file (no mathlib).
  2. Runs Lean in probe mode: Lean enumerates all atom assignments, filters to
     the constraint-satisfying valid worlds, and computes the list of
     counterexamples (valid assignments where the two flows disagree).
  3. Appends classification theorems matching what Lean found —
     `counterexamples = []` (EQUIVALENT) or `counterexamples.length = N` plus
     non-emptiness (DIVERGENT) — and re-runs Lean so the kernel checks the
     proofs (`by decide`). The proof file is kept under lean/cases/.
  4. Cross-checks Lean's verdict and counts against examples/verdicts.json
     (produced independently by tools/verify_extractions.py). A disagreement
     means a codegen bug — the two implementations are independent oracles.

The verdict is decided by Lean, not by Python.
"""

import json
import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from check_examples import EXAMPLES, load  # noqa: E402

REPO = EXAMPLES.parent
LEAN_CASES = REPO / "lean" / "cases"


def camel(case_id):
    return "".join(w.capitalize() for w in re.split(r"[-_]", case_id))


def topo_order(flow):
    """Post-order DFS from entry: every node appears after its children."""
    nodes = {n["id"]: n for n in flow["nodes"]}
    order, seen = [], set()

    def dfs(nid):
        if nid in seen:
            return
        seen.add(nid)
        node = nodes[nid]
        if node["type"] == "decision":
            dfs(node["true"])
            dfs(node["false"])
        order.append(nid)

    dfs(flow["entry"])
    return [nodes[nid] for nid in order]


def emit_flow(prefix, flow):
    lines = []
    for node in topo_order(flow):
        name = f"{prefix}_{node['id']}"
        if node["type"] == "outcome":
            lines.append(f"def {name} (_ : Assignment) : Outcome := .{node['outcome']}")
        else:
            lines.append(
                f"def {name} (a : Assignment) : Outcome :=\n"
                f"  if a.{node['atom']} then {prefix}_{node['true']} a else {prefix}_{node['false']} a"
            )
    lines.append(f"def {prefix} : Assignment → Outcome := {prefix}_{flow['entry']}")
    return "\n".join(lines)


def emit_valid(constraints):
    terms = []
    for c in constraints:
        if c["type"] == "implies":
            terms.append(f"(!a.{c['if']} || a.{c['then']})")
        else:  # excludes
            terms.append(f"!(a.{c['a']} && a.{c['b']})")
    if not terms:
        return "def valid (_ : Assignment) : Bool :=\n  true"
    body = "\n  && ".join(terms)
    return f"def valid (a : Assignment) : Bool :=\n  {body}"


def emit_source(case, ref_flow, ext_flow, theorems=None):
    atoms = [a["id"] for a in ref_flow["ontology"]["atoms"]]
    outcomes = [o["id"] for o in ref_flow["ontology"]["outcomes"]]
    constraints = ref_flow["ontology"].get("constraints", [])

    fields = "\n".join(f"  {a} : Bool" for a in atoms)
    ctors = "\n".join(f"  | {o}" for o in outcomes)
    enum = "\n".join(
        f"  bools.flatMap fun {a} =>" for a in atoms[:-1]
    ) + f"\n  bools.map fun {atoms[-1]} =>\n    {{ {', '.join(atoms)} }}"

    src = f"""/-
Machine-generated by tools/lean_verify.py — do not edit.

Case:      {case['id']}
Reference: {case['flow']}   (flow id: {ref_flow['id']})
Extracted: {case['extracted']}
Document:  {case['document']}

Verifies whether the flow extracted from the document is equivalent to the
reference flow over every assignment satisfying the ontology constraints.
Lean toolchain: 4.32.1, core only (no mathlib).
-/
set_option maxRecDepth 100000

structure Assignment where
{fields}
deriving Repr, DecidableEq

inductive Outcome where
{ctors}
deriving Repr, DecidableEq, BEq

{emit_valid(constraints)}

-- Reference flow ({ref_flow['id']})
{emit_flow("reference", ref_flow)}

-- Extracted flow (from {case['document']})
{emit_flow("extracted", ext_flow)}

def bools : List Bool := [false, true]

/-- Every assignment of the {len(atoms)} atoms ({2 ** len(atoms)} in total). -/
def allAssignments : List Assignment :=
{enum}

/-- Valid assignments where the two flows disagree. -/
def counterexamples : List Assignment :=
  allAssignments.filter fun a => valid a && !(reference a == extracted a)

#eval IO.println s!"TOTAL {{allAssignments.length}}"
#eval IO.println s!"VALID {{(allAssignments.filter valid).length}}"
#eval IO.println s!"COUNTEREXAMPLES {{counterexamples.length}}"
#eval counterexamples.forM fun a => IO.println s!"CX {{reprStr a}}"
"""
    if theorems:
        src += "\n" + theorems + "\n"
    return src


def theorems_for(n):
    if n == 0:
        return """/-- The document implements the reference logic exactly: on every legally
possible assignment the two flows agree. Kernel-checked by `decide`. -/
theorem equivalent : counterexamples = [] := by decide

theorem equivalent_all :
    allAssignments.all (fun a => !valid a || (reference a == extracted a)) = true := by
  decide"""
    return f"""/-- The document diverges from the reference logic: there is a legally
possible assignment on which the two flows disagree. Kernel-checked. -/
theorem divergent : counterexamples ≠ [] := by decide

/-- Exactly {n} valid assignments diverge. Kernel-checked. -/
theorem divergent_count : counterexamples.length = {n} := by decide"""


def run_lean(path):
    return subprocess.run(
        ["lean", str(path)], capture_output=True, text=True, timeout=600
    )


def main():
    LEAN_CASES.mkdir(parents=True, exist_ok=True)
    index = load("index.json")
    oracle = {v["case"]: v for v in load("verdicts.json")["verdicts"]}
    failures = 0

    for case in index["cases"]:
        cid = case["id"]
        try:
            ref_flow = load(case["flow"])
            ext_flow = load(case["extracted"])["flow"]
            path = LEAN_CASES / f"{camel(cid)}.lean"

            # Pass 1 — probe: Lean computes the counterexamples.
            path.write_text(emit_source(case, ref_flow, ext_flow))
            probe = run_lean(path)
            assert probe.returncode == 0, f"probe failed:\n{probe.stderr or probe.stdout}"
            counts = dict(
                (m.group(1), int(m.group(2)))
                for m in re.finditer(r"^(TOTAL|VALID|COUNTEREXAMPLES) (\d+)$", probe.stdout, re.M)
            )
            n = counts["COUNTEREXAMPLES"]
            verdict = "EQUIVALENT" if n == 0 else "DIVERGENT"

            # Pass 2 — proof: kernel-check the classification theorems.
            path.write_text(emit_source(case, ref_flow, ext_flow, theorems_for(n)))
            proof = run_lean(path)
            assert proof.returncode == 0, f"proof failed:\n{proof.stderr or proof.stdout}"

            # Cross-check against the independent Python oracle.
            o = oracle[cid]
            assert verdict == o["verdict"], f"Lean {verdict} != oracle {o['verdict']}"
            assert n == o["diverging_assignment_count"], (
                f"Lean found {n} counterexamples, oracle {o['diverging_assignment_count']}"
            )
            assert counts["VALID"] == o["valid_assignments"], (
                f"Lean valid={counts['VALID']}, oracle {o['valid_assignments']}"
            )

            print(
                f"  ok  {cid}: {verdict}"
                + (f" ({n}/{counts['VALID']} valid assignments)" if n else "")
                + f" — proof checked ({path.relative_to(REPO)})"
            )
        except AssertionError as e:
            failures += 1
            print(f"FAIL  {cid}: {e}")

    print(f"\n{len(index['cases'])} cases, {failures} failure(s)")
    sys.exit(1 if failures else 0)


if __name__ == "__main__":
    main()
